const MAX_EMAIL_VERIFICATION_ATTEMPTS = 5;
const EMAIL_VERIFICATION_CODE_EXPIRATION_TIME = 10 * 60 * 1000; // 10 minutes
const EMAIL_VERIFICATION_ATTEMPT_INTERVAL = 2 * 60 * 60 * 1000; // 2 hours

export { MAX_EMAIL_VERIFICATION_ATTEMPTS, EMAIL_VERIFICATION_CODE_EXPIRATION_TIME, EMAIL_VERIFICATION_ATTEMPT_INTERVAL };