import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as nodemailer from 'nodemailer';
import { EmailTemplateFactory } from './email-templates';

export interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  text?: string;
}

@Injectable()
export class EmailService {
  private readonly logger = new Logger(EmailService.name);
  private transporter: nodemailer.Transporter;

  constructor(private readonly configService: ConfigService) {
    this.initializeTransporter();
  }

  private initializeTransporter() {
    // Get SMTP configuration from environment variables
    const smtpHost = this.configService.get<string>('SMTP_HOST');
    const smtpUser = this.configService.get<string>('SMTP_USER');
    const smtpPass = this.configService.get<string>('SMTP_PASS');



    // Validate required environment variables
    if (!smtpHost || !smtpUser || !smtpPass) {
      this.logger.error('Missing required SMTP environment variables:', {
        SMTP_HOST: smtpHost || 'NOT SET',
        SMTP_USER: smtpUser || 'NOT SET',
        SMTP_PASS: smtpPass ? 'SET' : 'NOT SET'
      });
      return;
    }

    const emailConfig = {
      host: smtpHost,
      port: this.configService.get<number>('SMTP_PORT') || 587,
      secure: false, // Always false for port 587 (STARTTLS)
      requireTLS: true, // Require TLS for port 587
      ignoreTLS: false, // Don't ignore TLS
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    };

    // this.logger.log('Initializing SMTP transporter with config:', {
    //   host: emailConfig.host,
    //   port: emailConfig.port,
    //   secure: emailConfig.secure,
    //   user: emailConfig.auth.user
    // });

    this.transporter = nodemailer.createTransport(emailConfig);

    // Verify connection configuration
    this.transporter.verify((error) => {
      if (error) {
        this.logger.error('SMTP connection failed:', error);
      } else {
        this.logger.log('SMTP server is ready to send emails');
      }
    });
  }

  /**
   * Sends an email using the configured transporter
   * @param options - Email options including recipient, subject, and content
   * @returns Promise<boolean> - True if email was sent successfully
   */
  async sendEmail(options: EmailOptions): Promise<boolean> {
    try {
      // Check if transporter is properly initialized
      if (!this.transporter) {
        this.logger.error('SMTP transporter not initialized. Check your environment variables.');
        return false;
      }

      const mailOptions = {
        from: this.configService.get<string>('SMTP_FROM') || this.configService.get<string>('SMTP_USER'),
        to: options.to,
        subject: options.subject,
        html: options.html,
        text: options.text || this.stripHtml(options.html),
      };

      const info = await this.transporter.sendMail(mailOptions);
      this.logger.log(`Email sent successfully to ${options.to}. Message ID: ${info.messageId}`);
      
      return true;
    } catch (error) {
      this.logger.error(`Failed to send email to ${options.to}:`, error);
      return false;
    }
  }

  /**
   * Sends a welcome email to new users
   * @param email - User's email address
   * @param name - User's name
   * @param loginMethod - How the user signed up
   * @returns Promise<boolean> - True if email was sent successfully
   */
  async sendWelcomeEmail(email: string, name: string, loginMethod: 'google' | 'email' = 'email'): Promise<boolean> {
    const template = EmailTemplateFactory.createWelcomeTemplate();
    const html = template.generateWelcomeEmail({
      recipientName: name,
      loginMethod,
      subject: 'Welcome to Synapsy! 🎉',
      content: '' // Content is generated by template
    });

    return this.sendEmail({ to: email, subject: 'Welcome to Synapsy! 🎉', html });
  }

  /**
   * Sends a verification email
   * @param email - User's email address
   * @param verificationToken - Verification token
   * @param recipientName - Optional recipient name
   * @returns Promise<boolean> - True if email was sent successfully
   */
  async sendVerificationEmail(email: string, verificationToken: string, recipientName?: string): Promise<boolean> {
    const template = EmailTemplateFactory.createVerificationTemplate();
    const html = template.generateVerificationEmail({
      recipientName,
      verificationToken,
      subject: 'Verify Your Email - Synapsy',
      content: '' // Content is generated by template
    });

    return this.sendEmail({ to: email, subject: 'Verify Your Email - Synapsy', html });
  }

  /**
   * Sends a password reset email
   * @param email - User's email address
   * @param resetToken - Password reset token
   * @param recipientName - Optional recipient name
   * @returns Promise<boolean> - True if email was sent successfully
   */
  async sendPasswordResetEmail(email: string, resetToken: string, recipientName?: string): Promise<boolean> {
    const template = EmailTemplateFactory.createPasswordResetTemplate();
    const html = template.generatePasswordResetEmail({
      recipientName,
      resetToken,
      subject: 'Reset Your Password - Synapsy',
      content: '' // Content is generated by template
    });

    return this.sendEmail({ to: email, subject: 'Reset Your Password - Synapsy', html });
  }

  /**
   * Sends a verification success email
   * @param email - User's email address
   * @param recipientName - Optional recipient name
   * @returns Promise<boolean> - True if email was sent successfully
   */
  async sendVerificationSuccessEmail(email: string, recipientName?: string): Promise<boolean> {
    const template = EmailTemplateFactory.createVerificationSuccessTemplate();
    const html = template.generateVerificationSuccessEmail({
      recipientName,
      subject: '🎉 Email Verified Successfully - Welcome to Synapsy!',
      content: '' // Content is generated by template
    });

    return this.sendEmail({ to: email, subject: '🎉 Email Verified Successfully - Welcome to Synapsy!', html });
  }

  /**
   * Sends a password reset success email
   * @param email - User's email address
   * @param recipientName - Optional recipient name
   * @returns Promise<boolean> - True if email was sent successfully
   */
  async sendPasswordResetSuccessEmail(email: string, recipientName?: string): Promise<boolean> {
    const template = EmailTemplateFactory.createPasswordResetTemplate();
    const html = template.generatePasswordResetSuccessEmail({
      recipientName,
      subject: '🔒 Password Reset Successfully - Synapsy',
      content: '' // Content is generated by template
    });

    return this.sendEmail({ to: email, subject: '🔒 Password Reset Successfully - Synapsy', html });
  }

  /**
   * Sends a custom email using the custom template
   * @param email - User's email address
   * @param data - Custom email data
   * @returns Promise<boolean> - True if email was sent successfully
   */
  async sendCustomEmail(email: string, data: {
    title: string;
    content: string;
    recipientName?: string;
    showActionButton?: boolean;
    actionButtonText?: string;
    actionButtonUrl?: string;
    actionButtonColor?: string;
  }): Promise<boolean> {
    const template = EmailTemplateFactory.createCustomTemplate();
    const html = template.generateCustomEmail({
      recipientName: data.recipientName,
      customTitle: data.title,
      customContent: data.content,
      showActionButton: data.showActionButton,
      actionButtonText: data.actionButtonText,
      actionButtonUrl: data.actionButtonUrl,
      actionButtonColor: data.actionButtonColor,
      subject: data.title,
      content: '' // Content is generated by template
    });

    return this.sendEmail({ to: email, subject: data.title, html });
  }

  /**
   * Strips HTML tags from HTML content to create plain text version
   * @param html - HTML content
   * @returns string - Plain text content
   */
  private stripHtml(html: string): string {
    return html.replace(/<[^>]*>/g, '');
  }
}
